# This is a basic workflow to help you get started with Actions

name: CI Test Hunit

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs test with stack
      - name: Run test haskell with stack
        run: stack test

      # Runs a set of commands using the runners shell
      - name: Path for the hunit test
        run: cd test
        
      # Run test with HUnit
      - name: HUnit test
        run: runTestTT tests
